// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8HMNFKnEv7gJ55SbTqvTiU
// Component: Gvxz35rlhk
import * as React from "react";
import { useRouter } from "next/router";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import LandingClaimedButton from "../../LandingClaimedButton"; // plasmic-import: yyu20WZeYJ/component
import LandingPageAssets from "../../LandingPageAssets"; // plasmic-import: pvXv2nIO7t/component
import { DataProvider } from "@plasmicpkgs/plasmic-basic-components"; // plasmic-import: D4RbnlpRXg3/codeComponent
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_im_xbeanies.module.css"; // plasmic-import: 8HMNFKnEv7gJ55SbTqvTiU/projectcss
import sty from "./PlasmicItemsNav.module.css"; // plasmic-import: Gvxz35rlhk/css

export const PlasmicItemsNav__VariantProps = new Array();

export const PlasmicItemsNav__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicItemsNav__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return true ? (
    <p.Stack
      as={"div"}
      data-plasmic-name={"itemsNav"}
      data-plasmic-override={overrides.itemsNav}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.itemsNav
      )}
    >
      <LandingClaimedButton
        data-plasmic-name={"claimedButton2"}
        data-plasmic-override={overrides.claimedButton2}
        className={classNames("__wab_instance", sty.claimedButton2)}
      />

      <LandingClaimedButton
        data-plasmic-name={"unclaimedButton2"}
        data-plasmic-override={overrides.unclaimedButton2}
        className={classNames("__wab_instance", sty.unclaimedButton2)}
        unclaimedButton={true}
      />

      {true
        ? (
            (() => {
              try {
                return [
                  {
                    id: "640692cc177caf1ba51b7621",
                    tagUid: "04:7A:53:76:73:00:00",
                    mintId: "null",
                    mediaUrl:
                      "https://gateway.pinata.cloud/ipfs/QmREjM3TDrG931ecoNXMifpnVruFnzgw6Rv3DRpECLvVRp?_gl=1*6yrfy5*_ga*MTgzOTY5NDM1Mi4xNjc2NzUwMzUz*_ga_5RMPXG14TE*MTY3NzAzNDkzNy41LjAuMTY3NzAzNDk0MC41Ny4wLjA.%22,",
                    metadataUrl: "N/A",
                    issuer: "imNotArt",
                    claimed: true,
                    owner: "User X"
                  },
                  {
                    id: "640692cc177caf1ba51b7621",
                    tagUid: "04:7A:53:76:73:00:00",
                    mintId: "null",
                    mediaUrl:
                      "https://gateway.pinata.cloud/ipfs/QmREjM3TDrG931ecoNXMifpnVruFnzgw6Rv3DRpECLvVRp?_gl=1*6yrfy5*_ga*MTgzOTY5NDM1Mi4xNjc2NzUwMzUz*_ga_5RMPXG14TE*MTY3NzAzNDkzNy41LjAuMTY3NzAzNDk0MC41Ny4wLjA.%22,",
                    metadataUrl: "N/A",
                    issuer: "imNotArt",
                    claimed: false,
                    owner: "User X"
                  },
                  {
                    id: "640692cc177caf1ba51b7621",
                    tagUid: "04:7A:53:76:73:00:00",
                    mintId: "null",
                    mediaUrl:
                      "https://gateway.pinata.cloud/ipfs/QmREjM3TDrG931ecoNXMifpnVruFnzgw6Rv3DRpECLvVRp?_gl=1*6yrfy5*_ga*MTgzOTY5NDM1Mi4xNjc2NzUwMzUz*_ga_5RMPXG14TE*MTY3NzAzNDkzNy41LjAuMTY3NzAzNDk0MC41Ny4wLjA.%22,",
                    metadataUrl: "N/A",
                    issuer: "imNotArt",
                    claimed: false,
                    owner: "User X"
                  },
                  {
                    id: "640692cc177caf1ba51b7621",
                    tagUid: "04:7A:53:76:73:00:00",
                    mintId: "null",
                    mediaUrl:
                      "https://gateway.pinata.cloud/ipfs/QmREjM3TDrG931ecoNXMifpnVruFnzgw6Rv3DRpECLvVRp?_gl=1*6yrfy5*_ga*MTgzOTY5NDM1Mi4xNjc2NzUwMzUz*_ga_5RMPXG14TE*MTY3NzAzNDkzNy41LjAuMTY3NzAzNDk0MC41Ny4wLjA.%22,",
                    metadataUrl: "N/A",
                    issuer: "imNotArt",
                    claimed: true,
                    owner: "User X"
                  },
                  {
                    id: "640692cc177caf1ba51b7621",
                    tagUid: "04:7A:53:76:73:00:00",
                    mintId: "null",
                    mediaUrl:
                      "https://gateway.pinata.cloud/ipfs/QmREjM3TDrG931ecoNXMifpnVruFnzgw6Rv3DRpECLvVRp?_gl=1*6yrfy5*_ga*MTgzOTY5NDM1Mi4xNjc2NzUwMzUz*_ga_5RMPXG14TE*MTY3NzAzNDkzNy41LjAuMTY3NzAzNDk0MC41Ny4wLjA.%22,",
                    metadataUrl: "N/A",
                    issuer: "imNotArt",
                    claimed: true,
                    owner: "User X"
                  },
                  {
                    id: "640692cc177caf1ba51b7621",
                    tagUid: "04:7A:53:76:73:00:00",
                    mintId: "null",
                    mediaUrl:
                      "https://gateway.pinata.cloud/ipfs/QmREjM3TDrG931ecoNXMifpnVruFnzgw6Rv3DRpECLvVRp?_gl=1*6yrfy5*_ga*MTgzOTY5NDM1Mi4xNjc2NzUwMzUz*_ga_5RMPXG14TE*MTY3NzAzNDkzNy41LjAuMTY3NzAzNDk0MC41Ny4wLjA.%22,",
                    metadataUrl: "N/A",
                    issuer: "imNotArt",
                    claimed: false,
                    owner: "User X"
                  },
                  {
                    id: "640692cc177caf1ba51b7621",
                    tagUid: "04:7A:53:76:73:00:00",
                    mintId: "null",
                    mediaUrl:
                      "https://gateway.pinata.cloud/ipfs/QmREjM3TDrG931ecoNXMifpnVruFnzgw6Rv3DRpECLvVRp?_gl=1*6yrfy5*_ga*MTgzOTY5NDM1Mi4xNjc2NzUwMzUz*_ga_5RMPXG14TE*MTY3NzAzNDkzNy41LjAuMTY3NzAzNDk0MC41Ny4wLjA.%22,",
                    metadataUrl: "N/A",
                    issuer: "imNotArt",
                    claimed: true,
                    owner: "User X"
                  },
                  {
                    id: "640692cc177caf1ba51b7621",
                    tagUid: "04:7A:53:76:73:00:00",
                    mintId: "null",
                    mediaUrl:
                      "https://gateway.pinata.cloud/ipfs/QmREjM3TDrG931ecoNXMifpnVruFnzgw6Rv3DRpECLvVRp?_gl=1*6yrfy5*_ga*MTgzOTY5NDM1Mi4xNjc2NzUwMzUz*_ga_5RMPXG14TE*MTY3NzAzNDkzNy41LjAuMTY3NzAzNDk0MC41Ny4wLjA.%22,",
                    metadataUrl: "N/A",
                    issuer: "imNotArt",
                    claimed: false,
                    owner: "User X"
                  }
                ];
              } catch (e) {
                if (e instanceof TypeError) {
                  return [];
                }
                throw e;
              }
            })() ?? []
          ).map((nft, currentIndex) => (
            <div
              data-plasmic-name={"listOfAssets"}
              data-plasmic-override={overrides.listOfAssets}
              className={classNames(projectcss.all, sty.listOfAssets)}
              key={currentIndex}
            >
              <LandingPageAssets
                className={classNames(
                  "__wab_instance",
                  sty.landingPageAssets__y5J12
                )}
                landingUId={(() => {
                  try {
                    return nft.tagUid;
                  } catch (e) {
                    if (e instanceof TypeError) {
                      return "Claimed";
                    }
                    throw e;
                  }
                })()}
                unclaimedAssets={(() => {
                  try {
                    return nft.claimed;
                  } catch (e) {
                    if (e instanceof TypeError) {
                      return "unclaimedAssets";
                    }
                    throw e;
                  }
                })()}
              />
            </div>
          ))
        : null}

      <DataProvider
        data-plasmic-name={"data1"}
        data-plasmic-override={overrides.data1}
        className={classNames("__wab_instance", sty.data1)}
        data={[
          {
            id: "640692cc177caf1ba51b7621",
            tagUid: "04:7A:53:76:73:00:00",
            mintId: "null",
            mediaUrl:
              "https://gateway.pinata.cloud/ipfs/QmREjM3TDrG931ecoNXMifpnVruFnzgw6Rv3DRpECLvVRp?_gl=1*6yrfy5*_ga*MTgzOTY5NDM1Mi4xNjc2NzUwMzUz*_ga_5RMPXG14TE*MTY3NzAzNDkzNy41LjAuMTY3NzAzNDk0MC41Ny4wLjA.%22,",
            metadataUrl: "N/A",
            issuer: "imNotArt",
            claimed: true,
            owner: "User X"
          },
          {
            id: "640692cc177caf1ba51b7621",
            tagUid: "04:7A:53:76:73:00:00",
            mintId: "null",
            mediaUrl:
              "https://gateway.pinata.cloud/ipfs/QmREjM3TDrG931ecoNXMifpnVruFnzgw6Rv3DRpECLvVRp?_gl=1*6yrfy5*_ga*MTgzOTY5NDM1Mi4xNjc2NzUwMzUz*_ga_5RMPXG14TE*MTY3NzAzNDkzNy41LjAuMTY3NzAzNDk0MC41Ny4wLjA.%22,",
            metadataUrl: "N/A",
            issuer: "imNotArt",
            claimed: false,
            owner: "User X"
          },
          {
            id: "640692cc177caf1ba51b7621",
            tagUid: "04:7A:53:76:73:00:00",
            mintId: "null",
            mediaUrl:
              "https://gateway.pinata.cloud/ipfs/QmREjM3TDrG931ecoNXMifpnVruFnzgw6Rv3DRpECLvVRp?_gl=1*6yrfy5*_ga*MTgzOTY5NDM1Mi4xNjc2NzUwMzUz*_ga_5RMPXG14TE*MTY3NzAzNDkzNy41LjAuMTY3NzAzNDk0MC41Ny4wLjA.%22,",
            metadataUrl: "N/A",
            issuer: "imNotArt",
            claimed: false,
            owner: "User X"
          },
          {
            id: "640692cc177caf1ba51b7621",
            tagUid: "04:7A:53:76:73:00:00",
            mintId: "null",
            mediaUrl:
              "https://gateway.pinata.cloud/ipfs/QmREjM3TDrG931ecoNXMifpnVruFnzgw6Rv3DRpECLvVRp?_gl=1*6yrfy5*_ga*MTgzOTY5NDM1Mi4xNjc2NzUwMzUz*_ga_5RMPXG14TE*MTY3NzAzNDkzNy41LjAuMTY3NzAzNDk0MC41Ny4wLjA.%22,",
            metadataUrl: "N/A",
            issuer: "imNotArt",
            claimed: true,
            owner: "User X"
          },
          {
            id: "640692cc177caf1ba51b7621",
            tagUid: "04:7A:53:76:73:00:00",
            mintId: "null",
            mediaUrl:
              "https://gateway.pinata.cloud/ipfs/QmREjM3TDrG931ecoNXMifpnVruFnzgw6Rv3DRpECLvVRp?_gl=1*6yrfy5*_ga*MTgzOTY5NDM1Mi4xNjc2NzUwMzUz*_ga_5RMPXG14TE*MTY3NzAzNDkzNy41LjAuMTY3NzAzNDk0MC41Ny4wLjA.%22,",
            metadataUrl: "N/A",
            issuer: "imNotArt",
            claimed: true,
            owner: "User X"
          },
          {
            id: "640692cc177caf1ba51b7621",
            tagUid: "04:7A:53:76:73:00:00",
            mintId: "null",
            mediaUrl:
              "https://gateway.pinata.cloud/ipfs/QmREjM3TDrG931ecoNXMifpnVruFnzgw6Rv3DRpECLvVRp?_gl=1*6yrfy5*_ga*MTgzOTY5NDM1Mi4xNjc2NzUwMzUz*_ga_5RMPXG14TE*MTY3NzAzNDkzNy41LjAuMTY3NzAzNDk0MC41Ny4wLjA.%22,",
            metadataUrl: "N/A",
            issuer: "imNotArt",
            claimed: false,
            owner: "User X"
          },
          {
            id: "640692cc177caf1ba51b7621",
            tagUid: "04:7A:53:76:73:00:00",
            mintId: "null",
            mediaUrl:
              "https://gateway.pinata.cloud/ipfs/QmREjM3TDrG931ecoNXMifpnVruFnzgw6Rv3DRpECLvVRp?_gl=1*6yrfy5*_ga*MTgzOTY5NDM1Mi4xNjc2NzUwMzUz*_ga_5RMPXG14TE*MTY3NzAzNDkzNy41LjAuMTY3NzAzNDk0MC41Ny4wLjA.%22,",
            metadataUrl: "N/A",
            issuer: "imNotArt",
            claimed: true,
            owner: "User X"
          },
          {
            id: "640692cc177caf1ba51b7621",
            tagUid: "04:7A:53:76:73:00:00",
            mintId: "null",
            mediaUrl:
              "https://gateway.pinata.cloud/ipfs/QmREjM3TDrG931ecoNXMifpnVruFnzgw6Rv3DRpECLvVRp?_gl=1*6yrfy5*_ga*MTgzOTY5NDM1Mi4xNjc2NzUwMzUz*_ga_5RMPXG14TE*MTY3NzAzNDkzNy41LjAuMTY3NzAzNDk0MC41Ny4wLjA.%22,",
            metadataUrl: "N/A",
            issuer: "imNotArt",
            claimed: false,
            owner: "User X"
          }
        ]}
        name={"listOfAllNfts"}
      >
        <ph.DataCtxReader>
          {$ctx =>
            (
              (() => {
                try {
                  return $ctx.listOfAllNfts;
                } catch (e) {
                  if (e instanceof TypeError) {
                    return [];
                  }
                  throw e;
                }
              })() ?? []
            ).map((currentItem, currentIndex) => (
              <LandingPageAssets
                className={classNames(
                  "__wab_instance",
                  sty.landingPageAssets__g5WzD
                )}
                key={currentIndex}
                landingUId={(() => {
                  try {
                    return currentItem.tagUid;
                  } catch (e) {
                    if (e instanceof TypeError) {
                      return "Claimed";
                    }
                    throw e;
                  }
                })()}
                unclaimedAssets={currentItem.claimed}
              />
            ))
          }
        </ph.DataCtxReader>
      </DataProvider>
    </p.Stack>
  ) : null;
}

const PlasmicDescendants = {
  itemsNav: [
    "itemsNav",
    "claimedButton2",
    "unclaimedButton2",
    "listOfAssets",
    "data1"
  ],

  claimedButton2: ["claimedButton2"],
  unclaimedButton2: ["unclaimedButton2"],
  listOfAssets: ["listOfAssets"],
  data1: ["data1"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicItemsNav__ArgProps,
          internalVariantPropNames: PlasmicItemsNav__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicItemsNav__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "itemsNav") {
    func.displayName = "PlasmicItemsNav";
  } else {
    func.displayName = `PlasmicItemsNav.${nodeName}`;
  }
  return func;
}

export const PlasmicItemsNav = Object.assign(
  // Top-level PlasmicItemsNav renders the root element
  makeNodeComponent("itemsNav"),
  {
    // Helper components rendering sub-elements
    claimedButton2: makeNodeComponent("claimedButton2"),
    unclaimedButton2: makeNodeComponent("unclaimedButton2"),
    listOfAssets: makeNodeComponent("listOfAssets"),
    data1: makeNodeComponent("data1"),
    // Metadata about props expected for PlasmicItemsNav
    internalVariantProps: PlasmicItemsNav__VariantProps,
    internalArgProps: PlasmicItemsNav__ArgProps
  }
);

export default PlasmicItemsNav;
/* prettier-ignore-end */
