// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8HMNFKnEv7gJ55SbTqvTiU
// Component: VpUVU_G7VJ
import * as React from "react";
import { useRouter } from "next/router";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_im_xbeanies.module.css"; // plasmic-import: 8HMNFKnEv7gJ55SbTqvTiU/projectcss
import sty from "./PlasmicOwnerAddress.module.css"; // plasmic-import: VpUVU_G7VJ/css

export const PlasmicOwnerAddress__VariantProps = new Array();

export const PlasmicOwnerAddress__ArgProps = new Array("children");

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicOwnerAddress__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return true ? (
    <div
      data-plasmic-name={"ownerStack"}
      data-plasmic-override={overrides.ownerStack}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.ownerStack
      )}
    >
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {"Owner:"}
      </div>

      {p.renderPlasmicSlot({
        defaultContents: "Owner Address",
        value: args.children,
        className: classNames(sty.slotTargetChildren)
      })}
    </div>
  ) : null;
}

const PlasmicDescendants = {
  ownerStack: ["ownerStack", "text"],
  text: ["text"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicOwnerAddress__ArgProps,
          internalVariantPropNames: PlasmicOwnerAddress__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicOwnerAddress__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "ownerStack") {
    func.displayName = "PlasmicOwnerAddress";
  } else {
    func.displayName = `PlasmicOwnerAddress.${nodeName}`;
  }
  return func;
}

export const PlasmicOwnerAddress = Object.assign(
  // Top-level PlasmicOwnerAddress renders the root element
  makeNodeComponent("ownerStack"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),
    // Metadata about props expected for PlasmicOwnerAddress
    internalVariantProps: PlasmicOwnerAddress__VariantProps,
    internalArgProps: PlasmicOwnerAddress__ArgProps
  }
);

export default PlasmicOwnerAddress;
/* prettier-ignore-end */
