// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8HMNFKnEv7gJ55SbTqvTiU
// Component: bvKFXUs5yH
import * as React from "react";
import { useRouter } from "next/router";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { Video } from "@plasmicpkgs/plasmic-basic-components"; // plasmic-import: RhitNJW5Zu-/codeComponent
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_im_xbeanies.module.css"; // plasmic-import: 8HMNFKnEv7gJ55SbTqvTiU/projectcss
import sty from "./PlasmicVideoNft.module.css"; // plasmic-import: bvKFXUs5yH/css

export const PlasmicVideoNft__VariantProps = new Array();

export const PlasmicVideoNft__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicVideoNft__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <div
      data-plasmic-name={"rectangle5"}
      data-plasmic-override={overrides.rectangle5}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.rectangle5
      )}
    >
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {"IMAGE/VIDEO"}
      </div>

      <Video
        data-plasmic-name={"htmlVideo"}
        data-plasmic-override={overrides.htmlVideo}
        autoPlay={true}
        className={classNames("__wab_instance", sty.htmlVideo)}
        controls={true}
        muted={true}
        src={"https://vimeo.com/804521270"}
      />
    </div>
  );
}

const PlasmicDescendants = {
  rectangle5: ["rectangle5", "text", "htmlVideo"],
  text: ["text"],
  htmlVideo: ["htmlVideo"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicVideoNft__ArgProps,
          internalVariantPropNames: PlasmicVideoNft__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicVideoNft__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "rectangle5") {
    func.displayName = "PlasmicVideoNft";
  } else {
    func.displayName = `PlasmicVideoNft.${nodeName}`;
  }
  return func;
}

export const PlasmicVideoNft = Object.assign(
  // Top-level PlasmicVideoNft renders the root element
  makeNodeComponent("rectangle5"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),
    htmlVideo: makeNodeComponent("htmlVideo"),
    // Metadata about props expected for PlasmicVideoNft
    internalVariantProps: PlasmicVideoNft__VariantProps,
    internalArgProps: PlasmicVideoNft__ArgProps
  }
);

export default PlasmicVideoNft;
/* prettier-ignore-end */
